//var calcArea = require('./calcArea')
//console.log(calcArea)
//var table = calcArea.rectangle(4,1)
//console.log(table)
//var light = calcArea.circle(1)
//console.log(light)
//var testStuff = require('./test')
//console.log(testStuff)
//var calcVolume = require('./calcVolume')
//console.log(calcVolume)
//var container = calcVolume.rectangle(1,2,3)
//console.log(container)
var geometry = require('./geometry')
console.log(geometry)
var table = geometry.rectangle1(2,3)
console.log(table)
var container = geometry.rectangle2(1,2,3)
console.log(container)